### ISSUE TITLE
MVP Roadmap

### ISSUE THREAD

**Issue by UlisesGascon** [OpenPathfinder/visionBoard#30]
## Goals

Before starting MVP development, we completed a Proof of Concept (POC) ([official presentation](https://openjs-foundation.slack.com/archives/CTPN0DFF0/p1732199661737849), [video](https://www.youtube.com/watch?v=B1kd8k5SvBI), [source code](https://github.com/UlisesGascon/poc-openjs-security-program-standards-dashboard/blob/main/README.md), [slides](https://slides.ulisesgascon.com/openjs-security-program-standards/)). 

The primary goal of the MVP is to deprecate the old POC and redesign its components based on the feedback collected during and after its presentation.

The MVP will also enable several critical capabilities as we transition toward the product development phase:

- [x] **Enable external collaboration**: Provide tools, guides, and a clear way to identify tasks for contributors. Avoid requiring high-level access to GitHub APIs or infrastructure access for contributions.
- [x] **Support complex workflows**: Allow repository content analysis, enabling operations beyond the HTTP API capabilities of the POC.
- [x] **Smooth dashboard-website integration**: Ensure seamless integration with [the website](https://github.com/secure-dashboards/openjs-security-program-standards).
- [x] **Adopt a relational database**: Move away from the local filesystem database in favor of a relational database with features like migrations and seeding for improved ergonomics.

### ✅ [Milestone 1: Adopt a relational database and migrate away from the POC](https://github.com/secure-dashboards/openjs-foundation-dashboard/milestone/1)  

Transition from a local filesystem database to a relational database with robust features like migrations and seeding.

**Achieved**
- [x] Choose a database (Postgresql) and implement a development workflow (npm scripts (`npm run infra:start` and `npm run infra:stop`), [adminer](https://www.adminer.org/)...) using Docker (#1) ([Docs](https://github.com/secure-dashboards/openjs-foundation-dashboard#database-management))
- [x] Configure a SQL builder ([Knex](https://knexjs.org/)) and include the option to run migrations (`npm run db:migrate`), seeds (`npm run db:seed`), etc... (#2)([docs](https://github.com/secure-dashboards/openjs-foundation-dashboard#database-management))
- [x] Record GitHub orgs when adding a project (#21, #25)
- [x] Add workflow `update-github-orgs` (#23) ([docs](https://github.com/secure-dashboards/openjs-foundation-dashboard#workflows))
- [x] Add workflow `upsert-github-repositories` (#32) ([docs](https://github.com/secure-dashboards/openjs-foundation-dashboard#workflows))
- [x] Add seeds that allow to run the project without high level permissions (like GH tokens with org scope) (#34) ([docs](https://github.com/secure-dashboards/openjs-foundation-dashboard#seeding))
- [x] Include the table `compliance_checks` (#36)
- [x] Include the table `compliance_checks_alerts` (#40)
- [x] Include the table `compliance_checks_tasks` (#41)
- [x] Include the table `compliance_checks_results` (#42)

### ✅ [Milestone 2: Enable external collaboration](https://github.com/secure-dashboards/openjs-foundation-dashboard/milestone/2)

Provide tooling, guides, and accessible workflows to encourage contributor involvement without requiring high-level access.

**Achieved**
- [x] Add basic tooling for kickoff the ci pipelines including testing and linter (#3) ([docs](https://github.com/secure-dashboards/openjs-foundation-dashboard#development))
- [x] Include and update via scripts (`npm run db:generate-schema`) a database schema dump without the need to run the project locally and enable the option to port the schemas into a different tools (#4) ([docs](https://github.com/secure-dashboards/openjs-foundation-dashboard#schema-management), [schema](https://github.com/secure-dashboards/openjs-foundation-dashboard/blob/main/src/database/schema/schema.sql)) 
- [x] Add support to configuration (environmental variables, etc..) (#22) ([docs](https://github.com/secure-dashboards/openjs-foundation-dashboard#configuration))
- [x] Add a basic logger that is muted while running the tests (#24)
- [x] Add a GH pipeline that provide support (tasks, suggestions...) while dealing with migrations or checks (#47) ([docs](https://github.com/secure-dashboards/openjs-foundation-dashboard/blob/main/CONTRIBUTING.md#additional-support))
- [x] Add [CONTRIBUTING.md](https://github.com/secure-dashboards/openjs-foundation-dashboard/blob/main/CONTRIBUTING.md) guide with clear sections on [create a good PRs in this project](https://github.com/secure-dashboards/openjs-foundation-dashboard/blob/main/CONTRIBUTING.md#create-a-good-pr-in-this-project) and [How to add compliance checks](https://github.com/secure-dashboards/openjs-foundation-dashboard/blob/main/CONTRIBUTING.md#add-compliance-checks)
- [x] Add [SECURITY.md](https://github.com/secure-dashboards/openjs-foundation-dashboard/blob/main/SECURITY.md)
- [x] Add [CODEOWNERS](https://github.com/secure-dashboards/openjs-foundation-dashboard/blob/main/CODEOWNERS)
- [x] Add [Code of conduct (COC)](https://github.com/secure-dashboards/openjs-foundation-dashboard/blob/main/CODE_OF_CONDUCT.md)
- [x] Add issue templates
- [x] Create a solid [README.md](https://github.com/secure-dashboards/openjs-foundation-dashboard/blob/main/README.md)
- [x] @ulisesGascon Setup regular working meetings (every 2w) with collaborators in the OpenJS foundation calendar
- [x] @ulisesGascon Onboard the first contributors to the project
- [x] @ulisesGascon Land at least one compliance check developed by the community (Carlos, Iñigo, Tobias, Alpi...)

### ✅ [Milestone 3: Improve website integration](https://github.com/secure-dashboards/openjs-foundation-dashboard/milestone/3)  

Ensure seamless integration between the dashboard and the OpenJS Security Program Standards website.

**Achieved**
- [x] Support [website release 2.0](https://github.com/secure-dashboards/openjs-security-program-standards/releases/tag/2.0.0) by creating a script to download the content of `compliance_checks` in json format (#51)

### ✅ [Milestone 4: Enable artifacts generation](https://github.com/secure-dashboards/openjs-foundation-dashboard/milestone/4)  

Support the creation of artifacts such as reports, analysis results, and alerts, with mechanisms for notifying stakeholders.

**Achieved**
- [x] Include all the artifacts generation to an specific folder (`/output/*`) and avoid commit then by include a `.gitignore` rule 
- [x] @UlisesGascon Add an script to send the generated artifacts to a private artifact directory (TBC)
- [x] @UlisesGascon Migrate the legacy POC scripts/templates to the MVP and ensure that we can at least generate the same markdown samples but using the database this time
- [x] @inigomarquinez/@ulisesGascon brainstorm and generated web rich resources that can be embedded into the website (public dashboard information) as a POC 

### ✅ [Milestone 5: Ensure compatibility with diverse checks](https://github.com/secure-dashboards/openjs-foundation-dashboard/milestone/5)  

Support various types of checks, including manual tasks, automated workflows, and complex executors like long-running analyses.

**Achieved**
- [x] Add CLI and project addition capabilities (#5) ([Docs](https://github.com/secure-dashboards/openjs-foundation-dashboard/blob/main/README.md#workflows))
- [x] Add JSON Schemas validations for all the GH APIs endpoints in use (#20, #27 and #28)
- [x] Add CLI command `check list` (#37) ([docs](https://github.com/secure-dashboards/openjs-foundation-dashboard/blob/main/README.md#checks))
- [x] Add CLI command `check run` (#38) ([docs](https://github.com/secure-dashboards/openjs-foundation-dashboard/blob/main/README.md#checks))
- [x] Add workflow `run-all-checks` (#39) ([docs](https://github.com/secure-dashboards/openjs-foundation-dashboard/blob/main/README.md#workflows))
- [x] Land the first automated check (`githubOrgMFA`), including CLI integration (#44) and business logic (#43) with unit and integration tests in place. Also website manual addition of the query used by the dashboard (https://github.com/secure-dashboards/openjs-security-program-standards/pull/9)
- [x] Land a compliance check that relies on manual validation
- [x] Add support to run workflows that require long execution times using containers and child processes (#62)
- [x] @UlisesGascon Create issues to split workload for adding compliance checks
- [x] @UlisesGascon build and land a complex compliance check that requires to run a child process against all the repositories like the OSSF scorecard or similar.

**Comment by UlisesGascon** [comment]
At this stage MVP is completed, only waiting for #56

**Comment by bjohansebas** [comment]
I believe the MVP is now complete.
